# Generated by Django 3.0.5 on 2020-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModelsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('model_url', models.URLField()),
            ],
            options={
                'db_table': 'person_model',
                'ordering': ['-pub_time'],
            },
        ),
    ]
